### ISSUE TITLE
'Coordinator' object has no attribute 'refresh_plant'

### ISSUE THREAD

**Issue by silverclaw** [dewet22/givenergy-modbus#10]
* GivEnergy Modbus version: 75e7ab7a7a6207c1b5efc2be5745bb393d9d840d
* Python version: Python 3.8.9
* Operating System: MacOS 12.5

### Description

The dump-registers command fails to run.

The `refresh_plant` member function seems to have been removed in 1180ce162544481ccc1a4983041a53f908d0230a.

### What I Did

```
python3 cli.py --host "192.168.1.188" dump-registers --batteries 2

Traceback (most recent call last):
  File "cli.py", line 184, in <module>
    main(obj={})  # pragma: no cover
(...)
  File "cli.py", line 71, in dump_registers
    ctx.obj['CLIENT'].refresh_plant(plant=plant, full_refresh=True)
AttributeError: 'Coordinator' object has no attribute 'refresh_plant'
```

**Comment by dewet22** [comment]
The `Coordinator` class and the pre-1.0 API it was part of have been removed. The current library uses an async `Client` — see the README for usage. Closing as obsolete.
